#!/usr/bin/env node
// ─── gen-tokens.mjs ──────────────────────────────────────────────────────────
// src/styles/generated/motion.css from the vendored rime-shell motion.js, with
// Motion.qml's split: which roles are EFFECTS (kept under Reduce Motion, capped
// at 160 ms) and which are SPATIAL (0 under Reduce Motion). CSS transitions on
// the site read these variables and nothing else; there are no timing literals
// in the stylesheets.
//
//   node scripts/gen-tokens.mjs            write
//   node scripts/gen-tokens.mjs --check    fail if the committed file is stale
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as M from "../src/vendor/rime-shell/motion.mjs";
import { T1 } from "../src/geometry/theme.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/styles/generated/motion.css");
const REF = JSON.parse(readFileSync(join(ROOT, "src/vendor/rime-shell/SOURCE.json"), "utf8")).ref;

// Motion.qml:73-98
const EFFECT = ["micro", "hover", "state", "fadeIn", "fadeOut", "settle"];
const SPATIAL = ["contentDelay", "pressIn", "pressOut", "selection", "page", "surfaceEnterSmall", "surfaceExitSmall",
  "morphEnter", "morphExit", "notificationShift", "hero", "valueFollow", "errorShake", "staggerStep", "staggerCap"];
const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());
const S = M.speedScale("balanced", 1);

function durations(reduced, off) {
  const out = [];
  for (const k of EFFECT) out.push(`  --dur-${kebab(k)}: ${off ? 0 : M.effect(M.BASE[k], S, reduced)}ms;`);
  for (const k of SPATIAL) out.push(`  --dur-${kebab(k)}: ${off ? 0 : M.spatial(M.BASE[k], S, reduced)}ms;`);
  out.push(`  --press-scale: ${reduced || off ? 1 : M.PRESS_SCALE};`);
  out.push(`  --page-travel: ${reduced || off ? 0 : M.PAGE_TRAVEL}px;`);
  return out.join("\n");
}
const curves = Object.entries(M.CURVES).map(([k, c]) => `  --ease-${kebab(k)}: cubic-bezier(${c.slice(0, 4).join(", ")});`).join("\n");
const geo = [
  `  --notch-h: ${T1.notchHeight}px;`, `  --strip: ${T1.borderWidth}px;`, `  --notch-shoulder: ${T1.notchShoulder}px;`,
  `  --notch-bottom: ${T1.notchBottom}px;`, `  --radius-s: ${T1.radiusS}px;`, `  --radius-m: ${T1.radiusM}px;`,
  `  --radius-l: ${T1.radiusL}px;`, `  --radius-xl: ${T1.radiusXL}px;`,
].join("\n");

const css = `/* GENERATED by scripts/gen-tokens.mjs from rime-shell theme/motion.js and
 * theme/ThemeSet.qml @ ${REF.slice(0, 8)} — do not edit. Effects survive Reduce
 * Motion capped at ${M.REDUCED_EFFECT_CAP} ms; spatial roles go to 0 (Motion.qml). */
:root {
${durations(false, false)}
${curves}
${geo}
}
:root[data-motion="reduced"] {
${durations(true, false)}
}
@media (prefers-reduced-motion: reduce) {
  :root:not([data-motion]) {
${durations(true, false).replace(/^/gm, "  ")}
  }
}
:root[data-motion="off"] {
${durations(true, true)}
}
`;

if (process.argv.includes("--check")) {
  const cur = readFileSync(OUT, "utf8");
  if (cur !== css) { console.error("✗ src/styles/generated/motion.css is stale: run node scripts/gen-tokens.mjs"); process.exit(1); }
  console.log("✓ motion tokens current");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, css);
  console.log("wrote src/styles/generated/motion.css");
}
