#!/usr/bin/env node
// ─── gen-shapes.mjs ──────────────────────────────────────────────────────────
// The lock screen's password shapes, as the Shell draws them: runs rime-shell's
// own src/shapes/materialpath.js — over its vendored port of AndroidX
// graphics-shapes (Apache-2.0, src/shapes/material/LICENSE) — at build time and
// writes the seven paths PasswordShapes.qml rotates through to
// src/data/password-shapes.json. The QML-flavoured modules (`.pragma library`,
// `.import "x.js" as Name`) are evaluated with a tiny loader; their text is not
// changed.
//
//   node scripts/gen-shapes.mjs [--repo ../rime-shell] [--ref 6289d1f8]
// ─────────────────────────────────────────────────────────────────────────────
import { execFileSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";
import { dirname, join, resolve, posix } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const repo = resolve(opt("--repo", join(ROOT, "../rime-shell")));
const ref = opt("--ref", JSON.parse(readFileSync(join(ROOT, "src/vendor/rime-shell/SOURCE.json"), "utf8")).ref);
const show = (p) => execFileSync("git", ["-C", repo, "show", `${ref}:${p}`], { encoding: "utf8" });

const cache = new Map();
function load(path) {
  if (cache.has(path)) return cache.get(path);
  const text = show(path);
  const deps = [];
  const body = text
    .replace(/^\s*\.pragma\s+library\s*$/m, "")
    .replace(/^\s*\.import\s+"([^"]+)"\s+as\s+(\w+)\s*;?\s*$/gm, (_, rel, name) => {
      deps.push([name, posix.join(posix.dirname(path), rel)]);
      return "";
    });
  // Every top-level declaration is an export of a QML JS resource.
  const names = new Set();
  for (const m of body.matchAll(/^(?:function\s+(\w+)|(?:var|let|const)\s+(\w+)|class\s+(\w+))/gm)) names.add(m[1] || m[2] || m[3]);
  const exportsObj = {};
  cache.set(path, exportsObj);
  const args = deps.map((d) => d[0]);
  const vals = deps.map((d) => load(d[1]));
  const fn = new Function(...args, `${body}\nreturn { ${[...names].join(", ")} };`);
  Object.assign(exportsObj, fn(...vals));
  return exportsObj;
}

const mp = load("src/shapes/materialpath.js");
// PasswordShapes.qml's rotation, in its order.
const KINDS = ["clover4Leaf", "arrow", "pill", "softBurst", "diamond", "clamShell", "pentagon"];
const SIZE = 100;
const shapes = {};
for (const k of KINDS) {
  if (!mp.has(k)) throw new Error(`materialpath.js has no shape "${k}"`);
  shapes[k] = mp.path(k, SIZE);
}
const pq = show("src/components/auth/PasswordShapes.qml");
for (const k of KINDS) if (!pq.includes(k)) throw new Error(`PasswordShapes.qml no longer uses "${k}"`);
writeFileSync(join(ROOT, "src/data/password-shapes.json"), JSON.stringify({
  $comment: "GENERATED by scripts/gen-shapes.mjs from rime-shell's materialpath.js (AndroidX graphics-shapes port, Apache-2.0).",
  ref, size: SIZE, order: KINDS, shapes,
  licence: "Apache-2.0 (rime-shell src/shapes/material/LICENSE); upstream end-4/rounded-polygon-qmljs, a port of AndroidX androidx.graphics.shapes",
}, null, 2) + "\n");
console.log(`wrote src/data/password-shapes.json (${KINDS.length} shapes @ ${ref.slice(0, 8)})`);
