#!/usr/bin/env node
// ─── sync-shell.mjs ──────────────────────────────────────────────────────────
// The website does not have its own motion system, colour roles or fluid
// geometry. It runs Rime Shell's: the four pure-JS files below, copied byte for
// byte from a pinned rime-shell revision into src/vendor/rime-shell/, each with
// a generated ESM shim beside it (the originals end in a `module.exports`
// guard, which is dead code in a browser module).
//
//   node scripts/sync-shell.mjs [--ref <rev>] [--repo <path>]
//       re-vendor from a rime-shell checkout (default ../rime-shell) at <rev>
//       (default: the ref recorded in SOURCE.json) and rewrite SOURCE.json.
//   node scripts/sync-shell.mjs --check-hashes
//       offline: the vendored files still hash to what SOURCE.json records.
//       Runs before every build.
//   node scripts/sync-shell.mjs --check-upstream
//       the vendored files equal `git show <ref>:<path>` in the checkout.
//
// Spec §3.2 / §10.3: "the long-term goal is a shared JS source or generated
// token file". Until rime-shell publishes one, this is the generated copy, and
// a drift is a build failure rather than a slow divergence.
// ─────────────────────────────────────────────────────────────────────────────
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/vendor/rime-shell");
const SOURCE = join(OUT, "SOURCE.json");

// path in rime-shell → the names its module.exports block exposes.
const FILES = {
  "src/theme/motion.js": [
    "BASE", "LOOPS", "SPRINGS", "spring", "EXPRESSIVE", "expressive", "SPEEDS",
    "SCALE_MIN", "SCALE_MAX", "REDUCED_EFFECT_CAP", "PRESS_SCALE", "PAGE_TRAVEL",
    "CURVES", "speedScale", "spatial", "effect", "legacyDuration", "ease",
  ],
  "src/theme/spring.js": ["step", "atRest", "settleTime"],
  "src/theme/roles.js": ["rgb", "mix", "channel", "luminance", "contrast", "TARGETS", "hover", "pressed", "resolve"],
  "src/shapes/fluid/geometry.js": null, // read from its own module.exports block
};

const args = process.argv.slice(2);
const flag = (n) => args.includes(n);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const sha256 = (s) => createHash("sha256").update(s).digest("hex");

function exportsOf(text, path) {
  const m = text.match(/module\.exports\s*=\s*\{([\s\S]*?)\};?\s*$/);
  if (!m) throw new Error(`${path}: no trailing module.exports block`);
  return [...m[1].matchAll(/([A-Za-z_$][\w$]*)\s*:/g)].map((x) => x[1]);
}

function shim(file, names) {
  const base = file.split("/").pop();
  return `// GENERATED by scripts/sync-shell.mjs — do not edit.\n` +
    `// ESM view of ./${base}, which is rime-shell's own file, byte for byte.\n` +
    `// @ts-nocheck\n` +
    `import "./${base}.raw.js";\n` +
    `const g = globalThis.__rimeShell["${base}"];\n` +
    names.map((n) => `export const ${n} = g.${n};`).join("\n") + "\n";
}

// The raw file is wrapped so its top-level `var`/`function` declarations live
// in one function scope and are published under a single global, which keeps
// the shell's text untouched between the two marker lines.
function wrapped(text, base, names) {
  return `// GENERATED by scripts/sync-shell.mjs — the lines between the markers are\n` +
    `// rime-shell's ${base} verbatim; SOURCE.json records their sha256.\n` +
    `// @ts-nocheck\n` +
    `(function () {\nvar module = undefined;\n// ── BEGIN VERBATIM ──\n` +
    text +
    `// ── END VERBATIM ──\n` +
    `(globalThis.__rimeShell || (globalThis.__rimeShell = {}))["${base}"] = { ${names.join(", ")} };\n` +
    `})();\n`;
}

function verbatimOf(wrappedText) {
  const a = wrappedText.indexOf("// ── BEGIN VERBATIM ──\n");
  const b = wrappedText.lastIndexOf("// ── END VERBATIM ──\n");
  if (a < 0 || b < 0) throw new Error("vendored file lost its verbatim markers");
  return wrappedText.slice(a + "// ── BEGIN VERBATIM ──\n".length, b);
}

if (flag("--check-hashes") || flag("--check-upstream")) {
  const src = JSON.parse(readFileSync(SOURCE, "utf8"));
  let bad = 0;
  for (const [path, rec] of Object.entries(src.files)) {
    const base = path.split("/").pop();
    const text = verbatimOf(readFileSync(join(OUT, `${base}.raw.js`), "utf8"));
    if (sha256(text) !== rec.sha256) { console.error(`✗ ${base}: edited locally (sha256 differs from SOURCE.json)`); bad++; }
    if (flag("--check-upstream")) {
      const repo = resolve(opt("--repo", join(ROOT, "../rime-shell")));
      const up = execFileSync("git", ["-C", repo, "show", `${src.ref}:${path}`], { encoding: "utf8" });
      if (up !== text) { console.error(`✗ ${base}: differs from rime-shell ${src.ref}:${path}`); bad++; }
    }
  }
  if (bad) process.exit(1);
  console.log(`✓ vendored rime-shell files match ${src.ref.slice(0, 8)} (${Object.keys(src.files).length} files)`);
  process.exit(0);
}

const repo = resolve(opt("--repo", join(ROOT, "../rime-shell")));
const prev = existsSync(SOURCE) ? JSON.parse(readFileSync(SOURCE, "utf8")) : null;
const ref = execFileSync("git", ["-C", repo, "rev-parse", opt("--ref", prev?.ref ?? "origin/main")], { encoding: "utf8" }).trim();
mkdirSync(OUT, { recursive: true });
const record = { repo: "https://github.com/AndreNijman/rime-shell", ref, vendoredAt: new Date().toISOString(), files: {} };
for (const [path, listed] of Object.entries(FILES)) {
  const text = execFileSync("git", ["-C", repo, "show", `${ref}:${path}`], { encoding: "utf8" });
  const names = listed ?? exportsOf(text, path);
  const found = exportsOf(text, path);
  for (const n of names) if (!found.includes(n)) throw new Error(`${path}: ${n} is no longer exported`);
  const base = path.split("/").pop();
  writeFileSync(join(OUT, `${base}.raw.js`), wrapped(text, base, names));
  writeFileSync(join(OUT, base.replace(/\.js$/, ".mjs")), shim(base, names));
  record.files[path] = { sha256: sha256(text), exports: names };
  console.log(`vendored ${path} @ ${ref.slice(0, 8)} (${names.length} exports)`);
}
// MIT: the notice travels with the copies.
writeFileSync(join(OUT, "LICENSE"), execFileSync("git", ["-C", repo, "show", `${ref}:LICENSE`], { encoding: "utf8" }));
writeFileSync(SOURCE, JSON.stringify(record, null, 2) + "\n");
